SELECT ANIMAL_ID, NAME FROM ANIMAL_INS
WHERE NAME IN ('Diablo', 'Miller', 'Cherokee')
ORDER BY ANIMAL_ID;

SELECT ANIMAL_ID, NAME FROM ANIMAL_INS
WHERE INTAKE_CONDITION NOT IN ('Aged')
ORDER BY ANIMAL_ID;